version: '2'
services:
  web:
    tty: true
    build: .
    command:
      - bash
      - -c
      - /var/www/entrypoint.sh
    environment:
      - port=8000
      - PYTHONIOENCODING=UTF-8
      - C_FORCE_ROOT="yes"
    network_mode: bridge
    volumes:
      - .:/var/www/:cached
    ports:
      - 8000:8000/tcp
      - 2222:22/tcp
